[{
	"proID": 16,
	"proName": "江苏",
	"cities": [{
		"cityID": 183,
		"cityName": "徐州",
		"zones": [{
			"zoneID": 1746,
			"zoneName": "云龙",
			"streets": [{
				"streetID": 3273,
				"streetName": "民营工业园"
			}, {
				"streetID": 3275,
				"streetName": "云龙周边"
			}]
		}, {
			"zoneID": 1747,
			"zoneName": "鼓楼",
			"streets": [{
				"streetID": 3276,
				"streetName": "九里"
			}, {
				"streetID": 3277,
				"streetName": "金山桥"
			}, {
				"streetID": 3278,
				"streetName": "彭城广场"
			}, {
				"streetID": 3279,
				"streetName": "鼓楼周边"
			}]
		}, {
			"zoneID": 1748,
			"zoneName": "九里",
			"streets": ""
		}, {
			"zoneID": 1749,
			"zoneName": "贾汪",
			"streets": ""
		}, {
			"zoneID": 1750,
			"zoneName": "泉山",
			"streets": ""
		}, {
			"zoneID": 1751,
			"zoneName": "邳州",
			"streets": ""
		}, {
			"zoneID": 1752,
			"zoneName": "新沂",
			"streets": ""
		}, {
			"zoneID": 1753,
			"zoneName": "铜山",
			"streets": ""
		}, {
			"zoneID": 1754,
			"zoneName": "睢宁",
			"streets": ""
		}, {
			"zoneID": 1755,
			"zoneName": "沛县",
			"streets": ""
		}]
	}, {
		"cityID": 182,
		"cityName": "南京",
		"zones": ""
	}]
}]
